name: prettier

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
  prettier:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: |
        cd ./node_modules/.bin
        ./prettier --check "../../src/**/*.tsx"
